name: FunCombat
version: '1.0.0'
main: fc.keraune.funCombat.FunCombat
api-version: '1.21'
description: Sistema de PvP con knockback configurable
author: Keraune

commands:
  funcombat:
    description: Comandos de FunCombat
    usage: /funcombat <reload|status>
    permission: funcombat.admin

permissions:
  funcombat.admin:
    description: Permisos de administrador para FunCombat
    default: op